version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: ubuntu:22.04

    environment:
      CMAKE_VERSION: 3.22.1
      GPP_VERSION: 11
      CLANG_VERSION: 14

    steps:
      - checkout
      - run:
           name: Install dependencies
           command: |
             apt-get update
             apt-get install -y \
             build-essential cmake=${CMAKE_VERSION} g++-${GPP_VERSION} clang-${CLANG_VERSION} libsfml-dev
      - run: mkdir -p build
      - run: cd build && cmake ..
      - run: cd build && make
      - run: cd build && make install